### PR TITLE
Fix broken iterable comparison in sqlparser

### PR DESCRIPTION
**Pull request by kuhnroyal**
* this results in false positive migration tests, not sure what else could be effected

Hi @simolus3, maybe you can release a hotfix for this, really need this to work :)

### CODE REVIEW

**Comment by simolus3** [comment]
Ouch, thank you! I will release a hotfix today.

**Comment by simolus3** [comment]
Cherry-picked onto `master` and released as version `0.18.1` of sqlparser.

**Comment by kuhnroyal** [comment]
Thanks!

**Comment by kuhnroyal** [comment]
For anyone interested, the previously undetected comparison differences mainly revolved around missing `NOT NULL` or `DEFAULT X` constraints for me.

**Pull request merged**
