### PR TITLE
Append generated queries watchedTables to readsFrom.

### LINKED ISSUE #1275: table.column.isInQuery(subquery) doesn't watch tables
I've come across an issue where a table wasn't being updated when I expected it to and I think its related to a `table.column.isInQuery(subquery)`.

I was able to do a hacky fix by calling `notifyTables` on the table that was checking the subquery.

### PR DESCRIPTION
**Pull request by North101**
Fixes #1275

### CODE REVIEW

**Comment by simolus3** [comment]
Thanks! Could we have a small integration test for this? You can use the existing setup in `moor/test/integration_tests/moor_files_integration_test.dart`, I think the `readDynamic` query with a dynamic `WHERE` predicate could be used to test adding tables from an expression.

**Comment by simolus3** [comment]
I think the analysis warnings should go away after rebasing on 1a105f5fcfe7d2a94a823ff9d8eea4960125d026.

**Comment by North101** [comment]
> Thanks! Could we have a small integration test for this? You can use the existing setup in `moor/test/integration_tests/moor_files_integration_test.dart`, I think the `readDynamic` query with a dynamic `WHERE` predicate could be used to test adding tables from an expression.
Sure.

> I think the analysis warnings should go away after rebasing on [1a105f5](https://github.com/simolus3/moor/commit/1a105f5fcfe7d2a94a823ff9d8eea4960125d026).
Thanks, was trying to figure out why it was erring.

**Comment by North101** [comment]
> Thanks! Could we have a small integration test for this? You can use the existing setup in `moor/test/integration_tests/moor_files_integration_test.dart`, I think the `readDynamic` query with a dynamic `WHERE` predicate could be used to test adding tables from an expression.

I'm not sure how to test this

**Comment by simolus3** [comment]
I think like this should work with your PR. It currently times out on `develop`:

```dart
  test('updates for tables introduced in Dart subquery', () async {
    await db
        .into(db.config)
        .insert(ConfigCompanion.insert(configKey: 'my_key'));

    final inner = db.selectOnly(db.mytable)..addColumns([db.mytable.sometext]);
    final stream = db
        .readDynamic(predicate: (config) => config.configKey.isInQuery(inner))
        .watch();

    expect(stream, emitsInOrder([isEmpty, hasLength(1)]));

    await db
        .into(db.mytable)
        .insert(MytableCompanion.insert(sometext: const Value('my_key')));
  });
```

**Comment by North101** [comment]
> I think like this should work with your PR. It currently times out on `develop`:
> 
> ```dart
>   test('updates for tables introduced in Dart subquery', () async {
>     await db
>         .into(db.config)
>         .insert(ConfigCompanion.insert(configKey: 'my_key'));
> 
>     final inner = db.selectOnly(db.mytable)..addColumns([db.mytable.sometext]);
>     final stream = db
>         .readDynamic(predicate: (config) => config.configKey.isInQuery(inner))
>         .watch();
> 
>     expect(stream, emitsInOrder([isEmpty, hasLength(1)]));
> 
>     await db
>         .into(db.mytable)
>         .insert(MytableCompanion.insert(sometext: const Value('my_key')));
>   });
> ```

It worked. Thanks. I suspected it'd be something like that but I wasn't sure how to write the `expect(stream, emitsInOrder([isEmpty, hasLength(1)]));` part.

**Comment by simolus3** [comment]
LGTM, thanks!

**Pull request merged**
