### PR TITLE
Add virtual views and columns

### PR DESCRIPTION
**Pull request by westito**
Virtual views (projection) and virtual columns finally here 🎉

Typesafe, backward compatible!

Missing:
- Documentation
- Tests

(sorry for screenshots but syntax highlight helps reading)

**You can declare virtual columns and virtual views in table definition:**

```dart
class TodoItems extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text()();
  TextColumn get content => text()();
  IntColumn get priority => integer()();
  IntColumn get groupId => integer().references(TodoGroups, #id)();

  // Non-nullable virtual columns are included in queries by default
  TextColumn get titleWithContent =>
      text().virtual("todo_items.title || ': ' || todo_items.content")();

  // Nullable virtual columns are not included in queries by default
  // You must use 'addColumns' to add virtual columns to queries
  TextColumn get titleWithPriority => text()
      .virtual("todo_items.title || ' (' || todo_items.priority || ')'")
      .nullable()();

  // You can use virtual columns for join statements
  TextColumn get groupName => text().virtual('todo_groups.title').nullable()();

  // You can use auto-generated and custom class views too
  @override
  List<ViewDefinition> get views => [
        view('TodoPriorityListItem', columns: [id, titleWithPriority]),
        viewClass(TodoListItemWithGroupName, columns: [title, groupName]),
      ];
}
```
```dart
@UseRowClass(TodoGroupModel)
class TodoGroups extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text()();

  // You can use virtual column for groupBy statements
  // It is better than ".count()" expression, because you get the
  // count value in the model
  IntColumn get itemCount =>
      integer().virtual('COUNT(todo_items.id)').nullable()();

  @override
  List<ViewDefinition> get views => [
        view('TodoGroupWithCount', columns: [id, itemCount])
      ];
}
```
```dart
@UseRowClass(TodoGroupModel)
class TodoGroups extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text()();

  // You can use virtual column for groupBy statements
  // It is better than ".count()" expression, because you get the
  // count value in the model
  IntColumn get itemCount =>
      integer().virtual('COUNT(todo_items.id)').nullable()();

  @override
  List<ViewDefinition> get views => [
        view('TodoGroupWithCount', columns: [id, itemCount])
      ];
}
```
```dart
class TodoListItemWithGroupName {
  final String title;
  final String? groupName;

  TodoListItemWithGroupName(this.title, this.groupName);

  @override
  String toString() => 'TodoListItemWithGroupName(title: $title,'
      ' groupName: $groupName)';
}
```
**You can write simple queries to use it:**

```dart

  // You have to use JoinedSelectStatement for virtual columns
  print('-- Simple query without titleWithPriority --');
  final query1 = db.select(db.todoItems).join([]);
  for (final row in await query1.get()) {
    print(row.readTable(db.todoItems));
  }

  print('\n-- Simple query with titleWithPriority --');
  final query2 =
      db.select(db.todoItems).addColumns([db.todoItems.titleWithPriority]);
  for (final row in await query2.get()) {
    print(row.readTable(db.todoItems));
  }

  print('\n-- Todo view query with titleWithPriority --');
  final query3 = db
      .select(db.todoPriorityListItem)
      .addColumns([db.todoItems.titleWithPriority]);
  for (final row in await query3.get()) {
    print(row.readTable(db.todoPriorityListItem));
  }

  print('\n-- Todo view query with group name --');
  final query4 = db.select(db.todoListItemWithGroupName).join([
    innerJoin(
      db.todoGroups,
      db.todoGroups.id.equalsExp(db.todoItems.groupId),
      useColumns: false,
    )
  ])
    ..addColumns([db.todoItems.groupName]);

  for (final row in await query4.get()) {
    print(row.readTable(db.todoListItemWithGroupName));
  }

  print('\n-- Todo group query with todo count --');
  final query5 = db.select(db.todoGroupWithCount).join([
    innerJoin(
      db.todoItems,
      db.todoItems.groupId.equalsExp(db.todoGroups.id),
      useColumns: false,
    )
  ])
    ..addColumns([db.todoGroups.itemCount]);

  for (final row in await query5.get()) {
    print(row.readTable(db.todoGroupWithCount));
  }

  // You can use simple selects when all virtual columns are nullable
  print('\n-- Simple select group list --');
  final allGroups = await db.select(db.todoGroups).get();
  allGroups.forEach(print);

  // You can't use simple selects if you have non-nullable virtual columns!
  print('\n-- Simple select todo list --');
  try {
    final allItems = await db.select(db.todoItems).get();
    allItems.forEach(print);
  } catch (e) {
    print(e);
  }
```

**Output**

```
-- Simple query without titleWithPriority --
TodoItem(id: 1, title: A first entry, content: Content of first entry, priority: 3, groupId: 1, titleWithContent: A first entry: Content of first entry, titleWithPriority: null, groupName: null)
TodoItem(id: 2, title: Todo: Checkout drift, content: Drift is a persistence library for Dart and Flutter applications., priority: 6, groupId: 1, titleWithContent: Todo: Checkout drift: Drift is a persistence library for Dart and Flutter applications., titleWithPriority: null, groupName: null)
TodoItem(id: 3, title: Another entry added later, content: Content of another entry, priority: 1, groupId: 1, titleWithContent: Another entry added later: Content of another entry, titleWithPriority: null, groupName: null)

-- Simple query with titleWithPriority --
TodoItem(id: 1, title: A first entry, content: Content of first entry, priority: 3, groupId: 1, titleWithContent: A first entry: Content of first entry, titleWithPriority: A first entry (3), groupName: null)
TodoItem(id: 2, title: Todo: Checkout drift, content: Drift is a persistence library for Dart and Flutter applications., priority: 6, groupId: 1, titleWithContent: Todo: Checkout drift: Drift is a persistence library for Dart and Flutter applications., titleWithPriority: Todo: Checkout drift (6), groupName: null)
TodoItem(id: 3, title: Another entry added later, content: Content of another entry, priority: 1, groupId: 1, titleWithContent: Another entry added later: Content of another entry, titleWithPriority: Another entry added later (1), groupName: null)

-- Todo view query with titleWithPriority --
TodoPriorityListItem(id: 1, titleWithPriority: A first entry (3))
TodoPriorityListItem(id: 2, titleWithPriority: Todo: Checkout drift (6))
TodoPriorityListItem(id: 3, titleWithPriority: Another entry added later (1))

-- Todo view query with group name --
TodoListItemWithGroupName(title: A first entry, groupName: ToDo Group)
TodoListItemWithGroupName(title: Todo: Checkout drift, groupName: ToDo Group)
TodoListItemWithGroupName(title: Another entry added later, groupName: ToDo Group)

-- Todo group query with todo count --
TodoGroupWithCount(id: 1, itemCount: 3)

-- Simple select group list --
TodoGroupModel(id: 1, title: ToDo Group, itemCount: null)

-- Simple select todo list --
Null check operator used on a null value
```

### CODE REVIEW

**Comment by simolus3** [comment]
Thinking about this some more, I think that we should support two distinct features here:

1. Generated columns in the Dart DSL. These would compile directly to `GENERATED` columns in SQL, but with the usual restrictions that apply (they can only refer to columns in the same table, no subqueries, ...)
2. A Dart DSL for views, similar to the API you suggested (with `extends DslView`)

I have experimented with 1. a bit and I think I have found a nice API that shouldn't be to hard to implement in the generator. If that's ok for you, I'm happy to pick up your work and start with that API.

Theses features are a bit similar to the `virtual` columns feature that you're working on (where columns are purely virtual and not represented in the database at all). One reason for this is that I'd like to keep compatibility between Dart tables and Drift queries. But if we have virtual columns in a Dart table and then do `SELECT *  FROM that_table` in a Drift file, we'd have to rewrite the SQL to add the necessary columns. If we do that than this is fine for me, but it'll be a considerable amount of work to get right.
Using features already supported by sqlite3 (generated columns and views) will be more familiar to users and easier for us to implement and maintain.

**Comment by westito** [comment]
You're right. Generated columns would be more compatible with Drift queries. And DslView can achieve that non-generated virtual column feature. I would happy if you pick up this feature! Then I start working on my next idea 😄

**Comment by westito** [comment]
But it is depends on this DslView feature, so I do it later. 😄 It is a simple virtual "ObjectColumn" that is a placeholder for related objects
```dart
class TodoView extends DslView {
    IntColumn get id => integer().autoIncrement()();
    IntColumn get groupId => integer().references(TodoGroups, #id)();
    ObjectColumn get group => object<TodoGroup>()();
    // Or for sorter declaration:
    RefColumn get group => ref<TodoGroup>()();
}

final query = db.select(db.todoView).join([
    innerJoin(
      db.todoGroups,
      db.todoGroups.id.equalsExp(db.todoItems.groupId),
    )
  ]);

for (final row in await query.get()) {
    final todoView = row.readTable(db.todoView));
    todoView.group = row.readTable(db.todoGroup));
}
```
It isn't make automatic joins or eager loading, only create placeholders. So you don't have to create a row class just for related objects

**Comment by simolus3** [comment]
Small update on my progress picking up on this: Based on your awesome work here, I have started to add support for virtual columns in 3469bade62388aa1e708598151ca67c3bf4e0b5f and f2d086489091ea8ffe844eab57b364ed839dc120. There's still a lot to do and document, but it's getting there. I will also take a look at defining views in Dart with your API.

**Pull request closed without merging**
