### PR TITLE
Fix insertReturning stream update

### PR DESCRIPTION
**Pull request by kuhnroyal**
* test case not possible due to sqlite version
* related to #1096

### CODE REVIEW

**Comment by simolus3** [comment]
Thanks for this 👍 Can we also add a test similar to this one? https://github.com/simolus3/moor/blob/21cf78a361d502bfba9b225aa9359af06be0461b/moor/test/insert_test.dart#L61-L70

**Comment by kuhnroyal** [comment]
See description :)

**Comment by kuhnroyal** [comment]
We could try to add a test suite that only runs in CI and maybe ensure the correct version there.

**Comment by kuhnroyal** [comment]
I found the skips for this, refactored a little bit and added a test.

**Comment by kuhnroyal** [comment]
Hmm, managed to build the sqlite version in CI but it is not being used.

**Comment by simolus3** [comment]
Ah sorry, I should have read more carefully. The test I posted actually uses a mocked database implementation (mainly for historic reasons and so that it can reliably be tested on the web), so we may not even need the special setup.

**Comment by kuhnroyal** [comment]
Yes but the test still fails with a syntax error :(
And the tests don't mean much if they get skipped in CI.

**Comment by kuhnroyal** [comment]
Ok, CI now uses the manually built sqlite version and the test are all 3 running.

**Comment by simolus3** [comment]
Thanks :+1:

**Pull request merged**
